# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name="Farmer's name")),
                ('age', models.IntegerField(validators=['age_validator'])),
                ('Address', models.CharField(max_length=100)),
                ('contactno', models.IntegerField(validators=['contact_validator'])),
                ('familymember', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'farmers',
            },
        ),
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=50)),
                ('landarea', models.IntegerField(db_column='Land area in acers')),
                ('annualproduction', models.IntegerField(db_column='Production in Tonnes')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='farmers.Farmers')),
            ],
            options={
                'ordering': ['farmer'],
                'db_table': 'landdetails',
            },
        ),
    ]
