# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import farmers.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='contactno',
            field=models.BigIntegerField(validators=[farmers.models.contact_validator]),
        ),
    ]
