# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-13 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_landdetails_cropname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdetails',
            name='annualproduction',
            field=models.DecimalField(db_column='Production in Tonnes', decimal_places=1, max_digits=10),
        ),
    ]
