# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='indicatorname',
            field=models.CharField(max_length=50),
        ),
    ]
