# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-13 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Userslist',
        ),
    ]
