# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-05 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_auto_20190805_1353'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indicatortargets',
            table='indicatortargets',
        ),
    ]
