# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_auto_20190813_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=30, null=True)),
                ('mohala', models.CharField(max_length=50)),
                ('geographicalarea', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'urban',
            },
        ),
    ]
