# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-05 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_auto_20190805_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialyears',
            options={'ordering': ['year'], 'verbose_name_plural': 'Financial Years'},
        ),
    ]
