# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-05 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_auto_20190805_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatortargets',
            options={'verbose_name_plural': 'IndicatorTargets'},
        ),
    ]
