# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_auto_20190805_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themetics',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
