# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-07 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0010_auto_20190807_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themetics',
            options={'ordering': ['created'], 'verbose_name_plural': 'Themetics'},
        ),
    ]
