# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-08-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0013_indicatortargetachievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatortargetachievements',
            name='achievedtarget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='target_achieved', serialize=False, to='kpi.IndicatorTargets'),
        ),
    ]
